### ISSUE TITLE
[FEAT] Add ability to Control whether resources should be created

### ISSUE THREAD

**Issue by fdmsantos** [claranet/terraform-azurerm-aci#4]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like have a variable that gives me the possibility do delete everything. 
For example: 
-  Add new bool variable named create with default value to true.
- In all resources add count expression like this: count = var.create ? 1 : 0 (To resources with for_each expression, needs to be different)

With that, when i want to destroy everything, i only need to change the var.create variable to false.

Use Cases:

- In dev environment i would like to destroy all resources created by this module due cost optimization. But i dont want destroy all resources in my terraform project, because some resources like Storage Containers, File Shares contains data, so terraform destroy is not option.

I can submit PR to add this feature but i would like know if this is a feature you want to add before starting development.

### New or Affected Resource(s)/Data Source(s)

Probably All Resources will be affected

### Potential Terraform Configuration

```hcl
variable "create" {
  description = "Controls whether resources should be created"
  type        = bool
  default     = true
}

For all resources (except the resources that have for_each) add:
count = var.create ? 1 : 0

Also we need to change resources referencing, because now the resources will be indexed. Example:

TO get Container Group Name will change from azurerm_container_group.aci.name to azurerm_container_group.aci[0].name
```

**Comment by Shr3ps** [comment]
Hello,

I think there is no need of this.
You can just add a for_each on the module call directly at your terraform stack level:

```hcl
module "aci" {
  source  = "claranet/aci/azurerm"

  for_each = toset(var.create_aci ? ["enabled"] : [])
...
}
```

**Comment by fdmsantos** [comment]
Forget This. We can use count metadata in module since terraform 0.13. This is only needed for previous versions on terraform

**Comment by fdmsantos** [comment]
> Hello,
> 
> I think there is no need of this. You can just add a for_each on the module call directly at your terraform stack level:
> 
> ```terraform
> module "aci" {
>   source  = "claranet/aci/azurerm"
> 
>   for_each = toset(var.create_aci ? ["enabled"] : [])
> ...
> }
> ```

Yes you are right, this is an old project that i grabbed, and just noticed the terraform version is very old. I will instead update the terraform version. Thanks
